### ISSUE TITLE
Hey Vycka, as I said before great Lib!. But a question appeared: I use the TermFilter in a FixedTimeRange Query. The TermFilter has a string[] as a parameter and I wanted to query with different string values to get a Aggregate for each string Valuer. BUT only the last one is used in the ExecuteAggregate() query? Can you help me?

### ISSUE THREAD

**Issue by skind** [Vycka/ElasticSearch.Client#2] opened 2015-07-21 12:14 UTC
Yes, want to get the amount of each sold Car-'Type's by Country in a fixed time range in one Query:

QueryBuilder qB = new QueryBuilder();
qB.Filtered.Filter.Add( FilterType.Must, new FixedTimeRange("Sold_Date", fromDate, toDate));
qB.Filtered.Filter.Add( FilterType.Must, new TermFilter("COUNTRY", new string [] {"GERMANY", "FRANCE", "ITALY"}));
qB.Aggregates.Add("carTerm", new TermsAggregate("Type", 300));
DateHistogramAggregate aggregate = new DateHistogramAggregate("Sold_Date", "1d");
qB.Aggregates.Add("aggDH", aggregate);
Client.ExecuteAggregate(qB);

I hope this helps,
skind

**Comment by Vycka** [comment] 2015-07-21 21:08
Hey skind, little busy ATM, I hope its not urgent?
This sounds like it could be a bug, will try look into as soon as i get some spare time.
In the meantime, could you share code fragment what query is being built exactly?

Thank you.

**Comment by Vycka** [comment] 2015-07-23 19:52
Looked it up a little bit, will need to implement TermsFilter. (not TermFilter), hopefully will be finished by tomorrow evening,

There is a commit with it already developed, though TermsQuery needs to be finished for consistency and tests, so it can be published in nuget

**Comment by skind** [comment] 2015-07-24 09:56
..sounds good. 
As you are working on the LIB, another hint I discovered: After experimenting with different queries
I now got permanent(!) System.Exceptions --> BUT, with Fiddler Web Debugger I see that I got a '200' as Result AND the Result is delivered by Elasticsearch and it is complete! Only the LIB tells me an Exception:
"One or more shards returned failure [indexxxx/_search?search_type=count] 
at ...ElasticSearchQueryExecutor.ExecuteQueryInner[TResultModel](ElasticSearchQuery query, GetParam[] additionalGetParams) 
Do you know this strange behaviour and what is the reason for this? 
Thank you very much for your Support,
skind

**Comment by Vycka** [comment] 2015-07-24 10:27
TermsFilter implementation complete.
https://github.com/Vycka/ElasticSearch.Client/blob/59291d7af44724561dafa928561933cc7a7d00bd/src/ElasticSearch.Playground/Samples/Filters/TermsFilterTests.cs

This error is most likely because at least one of the indexes returned an error.
I agree that error handling could be better there, will look into that later

**Comment by Vycka** [comment] 2015-07-25 07:12
I modified that part, so exception will be returned only, when all shards fail the query.
You can get information about failed shard count by executing your query with ExecuteQueryCount, in result you will execute same search_type=count query, but will also get a result with included ElasticSearch result headers. Using them you can find result information by shards in result.Shards

```
        ElasticSearchResult result = client.ExecuteQueryCount(queryBuilder);

        Console.WriteLine(result.Aggregations.GetValue("count_by_correlation").ToString());
        Console.WriteLine(result.Aggregations.ResultObject.count_by_correlation.ToString());

        Console.WriteLine(result.Shards.Total + " " + result.Shards.Failed + "  " + result.Shards.Successful);
```

Update your nuget package and tell me if it helps.

**Comment by Vycka** [comment] 2015-09-01 15:21
Closing this for now, assuming, that the problem is solved

**Closed as completed by Vycka** 2015-09-01 15:21 UTC
